# Site settings
title: Code Vantage
email: stephen.smithwick@<gmail.com
description: >
  Welcome to Stephen Smithwick's blog,
  a collection of articles for developers.
baseurl: ""
url: "https://StephenSmithwick.github.io" # the base hostname & protocol for your site
github_urls:
  base: "https://github.com/StephenSmithwick/StephenSmithwick.github.io"
  edit: "https://github.com/StephenSmithwick/StephenSmithwick.github.io/edit/main"
  new: "https://github.com/StephenSmithwick/StephenSmithwick.github.io/new/main"
  raw: "https://github.com/StephenSmithwick/StephenSmithwick.github.io/raw/main"
  blob: "https://github.com/StephenSmithwick/StephenSmithwick.github.io/blob/main"
  tree: "https://github.com/StephenSmithwick/StephenSmithwick.github.io/tree/main"
comments:
  app_url: "https://stephen-smithwick-github-io-comment.vercel.app"
  # app_url: "http://localhost:3000"
github_username: StephenSmithwick
linkedin:
  name: Stephen Smithwick
  url: https://www.linkedin.com/in/stephen-smithwick-4674214/
logo: images/logo.jpeg
show_downloads: true
google_analytics: UA-60117878-2
permalink: none
emptyArray: []
collections:
  - resume
exclude:
  - state-cdk
  - js-frameworks

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
