brew "awscli"
brew "tree"
brew "wget"
brew "htop"
brew "nvtop"
brew "python"
brew "jq"
brew "watch"
brew "autoconf"
brew "automake"
brew "libtool"
brew "npm"
brew "yarn"
brew "ipython"
brew "node"
brew "rbenv"
brew "rbenv-gemset"
brew "languagetool"
brew "vale"
brew "bash-completion@2"

# Containers
brew "colima"
brew "docker"
# brew "podman"
# brew "k3d"

# Linux tools
brew "grep"
brew "zstd"
brew "coreutils"
brew "openssl"
brew "gnu-tar"
brew "curl"
brew "gnuplot"
brew "gawk"
brew "pandoc"
brew "java"
brew "entr"
brew "tailscale"
brew "go"
brew "ollama"

# Ops Tools
brew "minikube"

cask_args appdir: "/Applications"
cask "rectangle"
cask "google-chrome"
cask "visual-studio-code"
cask "zed"
cask "intellij-idea-ce"
cask "balenaetcher"
cask "caffeine"
cask "kdiff3"
cask "sqlworkbenchj"
cask "michaelvillar-timer"
cask "slack"
cask "marta"
cask "boop"
cask "shotcut"
cask "alacritty"
cask "chatgpt"
